version: '3.4'

networks:
  blog:

services:
  php:
    image: registry.gitlab.com/lellu/environement/php8.1
    container_name: blog-php
    restart: unless-stopped
    volumes:
      - ./:/var/www
    networks:
      - blog
  nginx:
    image: registry.gitlab.com/lellu/environement/nginx
    container_name: blog-nginx
    restart: unless-stopped
    ports:
      - "8002:80"
    volumes:
      - ./:/var/www
    networks:
      - blog
  
  mysql:
    image: mysql:8.0
    container_name: blog-mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - datamysql:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: blog
      MYSQL_PASSWORD: blog
    networks:
      - blog
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: blog-pma
    restart: unless-stopped
    environment:
      UPLOAD_LIMIT: 10000
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    links:
      - mysql
    depends_on:
      - mysql
    networks:
      - blog

volumes:
  datamysql:
